  name: bulebell
  version: 1.0.0
  mode: "dev"
  port: 8081
  start_time: "2021-01-01"
  machine_id: 1

  log:
    level: "info"
    file_name: bulebell.log
    max_size: 100
    max_age: 30
    max_backups: 10

  mysql:
    host: 127.0.0.1
    port: 3306
    user: root
    password: "123456"
    db_name: bluebell
    max_open_conns: 10
    max_idle_conns: 5

  redis:
    host: 127.0.0.1
    port: 6379
    password: ""
    db: 0
    pool_size: 10
  